The following ABNF grammar defines the joe example protocol:

    joe_proto       = *( HELLO | CHUNK | CLOSE | READY | ERROR )

    ;  No description                                                        

    HELLO           = signature %d1 filename aux
    signature       = %xAA %xA0             ; two octets
    filename        = string                ; 
    aux             = hash                  ; 

    ;  No description                                                        

    CHUNK           = signature %d2 filename offset size checksum data
    filename        = string                ; 
    offset          = number-8              ; 
    size            = number-8              ; 
    checksum        = number-8              ; 
    data            = chunk                 ; 

    ;  No description                                                        

    CLOSE           = signature %d3 filename size
    filename        = string                ; 
    size            = number-8              ; 

    ;  No description                                                        

    READY           = signature %d4

    ;  No description                                                        

    ERROR           = signature %d5 reason
    reason          = string                ; 

    ; A list of name/value pairs
    hash            = hash-count *( hash-name hash-value )
    hash-count      = number-4
    hash-value      = longstr
    hash-name       = string

    ; A chunk has 4-octet length + binary contents
    chunk           = number-4 *OCTET

    ; Strings are always length + text contents
    string          = number-1 *VCHAR
    longstr         = number-4 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-4        = 4OCTET
    number-8        = 8OCTET
