The following ABNF grammar defines the joe example protocol:

    joe_proto       = *( HELLO | READY | ERROR )

    ;  No description                                                        

    HELLO           = signature %d1 filename aux
    signature       = %xAA %xA0             ; two octets
    filename        = string                ; 
    aux             = hash                  ; 

    ;  No description                                                        

    READY           = signature %d2

    ;  No description                                                        

    ERROR           = signature %d3 reason
    reason          = string                ; 

    ; A list of name/value pairs
    hash            = hash-count *( hash-name hash-value )
    hash-count      = number-4
    hash-value      = longstr
    hash-name       = string

    ; Strings are always length + text contents
    string          = number-1 *VCHAR
    longstr         = number-4 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-4        = 4OCTET
